schema_version: 1
name: swell-staking
version: "0.1.0"
description: "Stake ETH with Swell Network to receive swETH or rswETH (EigenLayer restaking) on Ethereum mainnet"
author:
  name: "GeoGu360"
  github: "GeoGu360"
category: defi-protocol
tags:
  - staking
  - liquid-staking
  - restaking
  - swell
  - sweth
  - rsweth
  - eigenlayer
license: MIT

components:
  skill:
    dir: skills/swell-staking

build:
  lang: rust
  binary_name: swell-staking
  source_repo: GeoGu360/onchainos-plugins
  source_commit: "42159f23361032d508b3793c6402b5ef975132e5"
  source_dir: swell-staking

api_calls:
  - "https://ethereum.publicnode.com"
